

export const data = [
  {
    id: Math.random(),
    description: "do some shopping at maxland shopping mall",
    status: "Done",
    date: new Date('2023-10-2'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "fill my 12.5kg gas",
    status: "In progress",
    date: new Date('2023-08-11'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "hang out with friends for about 1hr",
    status: "Todo",
    date: new Date('2023-10-07'),
    priority: "Medium",
  },
  {
    id: Math.random(),
    description: "cut my hair",
    status: "Todo",
    date: new Date('2023-03-01'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-04-05'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "In progress",
    date: new Date('2023-09-03'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "spend some time with friends",
    status: "Done",
    date: new Date('2023-07-02'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-05-06'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "In progress",
    date: new Date('2023-04-09'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "spend some time with friends",
    status: "Done",
    date: new Date('2023-10-09'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "Done",
    date: new Date('2023-01-02'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "fill my 12.5kg gas",
    status: "In progress",
    date: new Date('2023-03-01'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "hang out with friends for about 1hr",
    status: "Todo",
    date: new Date('2023-12-02'),
    priority: "Medium",
  },
  {
    id: Math.random(),
    description: "cut my hair",
    status: "Todo",
    date: new Date('2023-12-07'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-06-04'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "In progress",
    date: new Date('2023-10-10'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "spend some time with friends",
    status: "Done",
    date: new Date('2023-03-23'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-04-28'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "In progress",
    date: new Date('2023-07-09'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "spend some time with friends ",
    status: "Done",
    date: new Date('2023-04-24'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "spend some time with friends",
    status: "Done",
    date: new Date('2023-04-11'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "hang out with friends for about 1hr",
    status: "Todo",
    date: new Date('2023-06-09'),
    priority: "Medium",
  },
  {
    id: Math.random(),
    description: "cut my hair",
    status: "Todo",
    date: new Date('2023-11-29'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-11-03'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "In progress",
    date: new Date('2023-07-28'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "spend some time with friends",
    status: "Done",
    date: new Date('2023-03-29'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-04-09'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "In progress",
    date: new Date('2023-09-22'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "In progress",
    date: new Date('2023-02-04'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "spend some time with friends",
    status: "Done",
    date: new Date('2023-04-04'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-11-03'),
    priority: "High",
  },


  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-12-15'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "In progress",
    date: new Date('2023-10-07'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "spend some time with friends",
    status: "Done",
    date: new Date('2023-02-05'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-03-09'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "hang out with friends for about 1hr",
    status: "Todo",
    date: new Date('2023-12-03'),
    priority: "Medium",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-12-01'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "hang out with friends for about 1hr",
    status: "Todo",
    date: new Date('2023-11-17'),
    priority: "Medium",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-11-17'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "In progress",
    date: new Date('2023-11-11'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "spend some time with friends",
    status: "Done",
    date: new Date(),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-10-13'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "In progress",
    date: new Date('2023-09-17'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "spend some time with friends",
    status: "Done",
    date: new Date('2023-09-15'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "hang out with friends for about 1hr",
    status: "Todo",
    date: new Date('2023-08-02'),
    priority: "Medium",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-07-01'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "In progress",
    date: new Date('2023-06-12'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "spend some time with friends",
    status: "Done",
    date: new Date('2023-06-13'),
    priority: "Low",
  },
  {
    id: Math.random(),
    description: "refill my car fuel tank",
    status: "In progress",
    date: new Date('2023-05-11'),
    priority: "High",
  },
  {
    id: Math.random(),
    description: "work on my project",
    status: "In progress",
    date: new Date('2023-04-10'),
    priority: "Low",
  },


  
];
